name: import-ig-to-preview

on:
  push:
    branches: ['master']
  workflow_dispatch:
  schedule:
    - cron: 10-59/15 * * * *

jobs:
  import-ig-to-preview:
    runs-on: ubuntu-latest
    steps:
      - run: "curl -X POST -v --location '${{secrets.CMS_URL}}/ig/import' --header 'Content-Type: application/json' --header 'Authorization: ${{secrets.CMS_AUTH}}' -d '{}'"
