name: upload-ig-to-cdn

on:
  push:
    branches: ['master']
  workflow_dispatch:
  schedule:
    - cron: 10-59/15 * * * *

env:
  CMS_URL: ${{secrets.CMS_URL}}
  CMS_AUTH: ${{secrets.CMS_AUTH}}

jobs:
  import-ig-to-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v4
        with:
          repository: learnmbti/cdn.learnmbti.com
          path: cdn
          token: ${{ secrets.GH_TOKEN }}
      - run: bun uploadIgToCdn.ts
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          # SSH_DEPLOY_KEY: ${{ secrets.TOAST_SSH_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: 'cdn'
          destination-github-username: learnmbti
          destination-repository-name: cdn.learnmbti.com
          target-branch: main